In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('csv_building_structure.csv',index_col="building_id")

In [2]:
df

district_id  vdcmun_id  ward_id  count_floors_pre_eq  \
building_id                                                          
120101000011           12       1207   120703                    1   
120101000021           12       1207   120703                    1   
120101000031           12       1207   120703                    1   
120101000041           12       1207   120703                    1   
120101000051           12       1207   120703                    1   
...                   ...        ...      ...                  ...   
366709001241           36       3603   360302                    2   
366709001251           36       3603   360302                    2   
366709001261           36       3603   360302                    2   
366709001271           36       3603   360302                    2   
366709001281           36       3603   360302                    2   

              count_floors_post_eq  age_building  plinth_area_sq_ft  \
building_id                                                           
120101000011                     1             9                288   
120101000021                     1            15                364   
120101000031                     1            20                384   
120101000041                     1            20                312   
120101000051                     1            30                308   
...                            ...           ...                ...   
366709001241                     0            60                165   
366709001251                     0            35                342   
366709001261                     0            35                342   
366709001271                     0            19                306   
366709001281                     0            12                840   

              height_ft_pre_eq  height_ft_post_eq land_surface_condition  ...  \
building_id                                                               ...   
120101000011                 9                  9                   Flat  ...   
120101000021                 9                  9                   Flat  ...   
120101000031                 9                  9                   Flat  ...   
120101000041                 9                  9                   Flat  ...   
120101000051                 9                  9                   Flat  ...   
...                        ...                ...                    ...  ...   
366709001241                18                  0                   Flat  ...   
366709001251                18                  0                   Flat  ...   
366709001261                18                  0                   Flat  ...   
366709001271                18                  0                   Flat  ...   
366709001281                18                  0                   Flat  ...   

             has_superstructure_mud_mortar_brick  \
building_id                                        
120101000011                                   0   
120101000021                                   0   
120101000031                                   0   
120101000041                                   0   
120101000051                                   0   
...                                          ...   
366709001241                                   0   
366709001251                                   0   
366709001261                                   0   
366709001271                                   0   
366709001281                                   0   

             has_superstructure_cement_mortar_brick has_superstructure_timber  \
building_id                                                                     
120101000011                                      0                         0   
120101000021                                      0                         0   
120101000031                                      0                         0   
120101000041                               

In [3]:
df.info

<bound method DataFrame.info of               district_id  vdcmun_id  ward_id  count_floors_pre_eq  \
building_id                                                          
120101000011           12       1207   120703                    1   
120101000021           12       1207   120703                    1   
120101000031           12       1207   120703                    1   
120101000041           12       1207   120703                    1   
120101000051           12       1207   120703                    1   
...                   ...        ...      ...                  ...   
366709001241           36       3603   360302                    2   
366709001251           36       3603   360302                    2   
366709001261           36       3603   360302                    2   
366709001271           36       3603   360302                    2   
366709001281           36       3603   360302                    2   

              count_floors_post_eq  age_building  plinth_

In [4]:
df = df.dropna()

In [5]:
df.select_dtypes("object").nunique()

land_surface_condition          3
foundation_type                 5
roof_type                       3
ground_floor_type               5
other_floor_type                4
position                        4
plan_configuration             10
condition_post_eq               8
damage_grade                    5
technical_solution_proposed     4
dtype: int64

In [6]:
df_1 = df[df['district_id'] == 12]

In [7]:
df.shape

(762094, 30)

In [8]:
df_1.shape

(39352, 30)

In [9]:
data = pd.get_dummies(df_1.drop(['district_id','vdcmun_id','ward_id','damage_grade','technical_solution_proposed'],axis=1),drop_first=True)
target = df_1['damage_grade']

In [10]:
data

count_floors_pre_eq  count_floors_post_eq  age_building  \
building_id                                                             
120101000011                    1                     1             9   
120101000021                    1                     1            15   
120101000031                    1                     1            20   
120101000041                    1                     1            20   
120101000051                    1                     1            30   
...                           ...                   ...           ...   
125609000711                    2                     2            20   
125609000721                    2                     2            30   
125609000731                    2                     0            15   
125609000741                    2                     2             8   
125609000751                    2                     2            30   

              plinth_area_sq_ft  height_ft_pre_eq  height_ft_post_eq  \
building_id                                                            
120101000011                288                 9                  9   
120101000021                364                 9                  9   
120101000031                384                 9                  9   
120101000041                312                 9                  9   
120101000051                308                 9                  9   
...                         ...               ...                ...   
125609000711                458                14                 14   
125609000721                320                12                 12   
125609000731                489                14                  0   
125609000741                458                14                 14   
125609000751                458                14                 14   

              has_superstructure_adobe_mud  \
building_id                                  
120101000011                             0   
120101000021                             0   
120101000031                             0   
120101000041                             0   
120101000051                             0   
...                                    ...   
125609000711                             0   
125609000721                             0   
125609000731                             0   
125609000741                             0   
125609000751                             0   

              has_superstructure_mud_mortar_stone  \
building_id                                         
120101000011                                    1   
120101000021                                    1   
120101000031                                    1   
120101000041                                    1   
120101000051                                    1   
...                                           ...   
125609000711                                    1   
125609000721                                    1   
125609000731                                    1   
125609000741                                    1   
125609000751                                    1   

              has_superstructure_stone_flag  \
building_id                                   
120101000011                              0   
120101000021                              0   
120101000031                              0   
120101000041                              0   
120101000051                              0   
...                                     ...   
125609000711                              0   
125609000721                              0   
125609000731                              0   
125609000741                              0   
125609000751                              0   

              has_superstructure_cement_mortar_stone  ...  \
building_id                                           ...   
120101000011                                       0  ...   
120101000021                               

In [11]:
data.shape

(39352, 51)

In [12]:
target.shape

(39352,)

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2, random_state=42)

clf = DecisionTreeClassifier(ccp_alpha=0.01)

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"准确率: {accuracy}")

准确率: 0.5727353576419769


In [14]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
conf_matrix = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[ 867  664    0    0    0]
 [   0  869  589  248    0]
 [   0  544  780  626    0]
 [   0  111  465  990    0]
 [   0    5   15   96 1002]]


In [15]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2, random_state=42)

model = MultinomialNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")


Accuracy: 0.5454198958200991


In [16]:

conf_matrix = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[1020  463   46    0    2]
 [ 215  931  356  200    4]
 [ 159  706  579  491   15]
 [  33  338  417  762   16]
 [   4   13   31   69 1001]]


In [17]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

model = LogisticRegression(multi_class='multinomial', solver='lbfgs')

# 训练模型
model.fit(X_train, y_train)

# 在测试集上进行预测
y_pred = model.predict(X_test)

# 输出混淆矩阵
conf_matrix = confusion_matrix(y_test, y_pred)
print("混淆矩阵:")
print(conf_matrix)

混淆矩阵:
[[ 744  183  602    1    1]
 [ 401  228 1064   12    1]
 [ 404  130 1385   23    8]
 [ 213   75 1180   68   30]
 [  12    3   77   17 1009]]


d:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [18]:
# 导入所需的库
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# 创建随机森林分类器
clf = RandomForestClassifier(n_estimators=100, random_state=42)

# 训练模型
clf.fit(X_train, y_train)

# 在测试集上进行预测
y_pred = clf.predict(X_test)

# 计算并输出准确率
accuracy = accuracy_score(y_test, y_pred)
print(f"准确率: {accuracy}")

# 输出混淆矩阵
conf_matrix = confusion_matrix(y_test, y_pred)
print("混淆矩阵:")
print(conf_matrix)


准确率: 0.5971287002922119
混淆矩阵:
[[1198  259   63   11    0]
 [ 277  767  451  207    4]
 [ 126  524  790  502    8]
 [  16  181  420  919   30]
 [   1    4   18   69 1026]]


In [ ]:
data.columns

Index(['count_floors_pre_eq', 'count_floors_post_eq', 'age_building',
       'plinth_area_sq_ft', 'height_ft_pre_eq', 'height_ft_post_eq',
       'has_superstructure_adobe_mud', 'has_superstructure_mud_mortar_stone',
       'has_superstructure_stone_flag',
       'has_superstructure_cement_mortar_stone',
       'has_superstructure_mud_mortar_brick',
       'has_superstructure_cement_mortar_brick', 'has_superstructure_timber',
       'has_superstructure_bamboo', 'has_superstructure_rc_non_engineered',
       'has_superstructure_rc_engineered', 'has_superstructure_other',
       'land_surface_condition_Moderate slope',
       'land_surface_condition_Steep slope',
       'foundation_type_Cement-Stone/Brick',
       'foundation_type_Mud mortar-Stone/Brick', 'foundation_type_Other',
       'foundation_type_RC', 'roof_type_Bamboo/Timber-Light roof',
       'roof_type_RCC/RB/RBC', 'ground_floor_type_Mud',
       'ground_floor_type_Other', 'ground_floor_type_RC',
       'ground_floor_type_Timb